import 'package:cloud_firestore/cloud_firestore.dart';

/// TenantUser represents a user account within a specific tenant.
/// Document path: `_platform/usuarios/{tenant_id}/{user_id}`.
/// The uid matches Firebase Auth UID (not autogenerated by Firestore).
/// Custom Claims in Firebase Auth contain: { tenant_id, role }.
class TenantUser {
  const TenantUser({
    required this.uid,
    required this.email,
    required this.nombre,
    required this.activo,
    required this.createdAt,
    this.updatedAt,
    this.lastLogin,
  });

  /// Firebase Auth UID (matches auth.uid).
  final String uid;

  /// User email address (denormalized from Firebase Auth).
  final String email;

  /// Full name of the user.
  final String nombre;

  /// Whether this user account is active.
  /// Inactive users are blocked from accessing their tenant's data.
  final bool activo;

  /// Timestamp when user was created.
  final DateTime createdAt;

  /// Timestamp when user was last modified.
  final DateTime? updatedAt;

  /// Timestamp of last successful login.
  final DateTime? lastLogin;

  /// Create TenantUser from Firestore document map.
  factory TenantUser.fromJson(String uid, Map<String, dynamic> json) {
    return TenantUser(
      uid: uid,
      email: json['email'] as String? ?? '',
      nombre: json['nombre'] as String? ?? '',
      activo: json['activo'] as bool? ?? true,
      createdAt:
          (json['created_at'] as Timestamp?)?.toDate() ?? DateTime.now(),
      updatedAt: (json['updated_at'] as Timestamp?)?.toDate(),
      lastLogin: (json['last_login'] as Timestamp?)?.toDate(),
    );
  }

  /// Convert to Firestore document map (snake_case keys).
  Map<String, dynamic> toJson() => {
        'email': email,
        'nombre': nombre,
        'activo': activo,
        'created_at': Timestamp.fromDate(createdAt),
        'updated_at': updatedAt == null
            ? FieldValue.serverTimestamp()
            : Timestamp.fromDate(updatedAt!),
        if (lastLogin != null) 'last_login': Timestamp.fromDate(lastLogin!),
      };

  /// Create a copy with optional field overrides.
  TenantUser copyWith({
    String? email,
    String? nombre,
    bool? activo,
    DateTime? createdAt,
    DateTime? updatedAt,
    DateTime? lastLogin,
  }) =>
      TenantUser(
        uid: uid,
        email: email ?? this.email,
        nombre: nombre ?? this.nombre,
        activo: activo ?? this.activo,
        createdAt: createdAt ?? this.createdAt,
        updatedAt: updatedAt ?? this.updatedAt,
        lastLogin: lastLogin ?? this.lastLogin,
      );
}
